language: minimal

sudo: required
services:
  - docker

before_install:
  - rake docker_compose:build
#  - docker tag test-app:latest vsuzdaltsev/test-app:latest
  - docker build -t vsuzdaltsev/test-app -f ./Dockerfile .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vsuzdaltsev/test-app:latest
