language: minimal

sudo: required
services:
  - docker

branches:
  only:
  - master

before_install:
  - rake docker_compose:build

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vsuzdaltsev/test_web_app:latest
