language: minimal

sudo: required
services:
  - docker

#branches:
#  only:
#  - master

before_install:
  - docker build -t vsuzdaltsev/test_web_app -f ./Dockerfile .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vsuzdaltsev/test_web_app:latest
