# frozen_string_literal: true

source 'https://rubygems.org'
ruby '2.6.5'
gem 'abstracts'
gem 'activesupport'
gem 'aws-sdk-secretsmanager'
gem 'minitest'
gem 'rack-test'
gem 'rspec'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'tzinfo-data'
gem 'unicorn'
gem 'pg'
